# Generated by Django 4.1.1 on 2022-10-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usuario_ultimo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_nome',
            field=models.CharField(max_length=16),
        ),
    ]
